### ISSUE TITLE
javax.imageio.IIOException: Can't read input file

### ISSUE THREAD

**Issue by bradenbest** [jameshong92/sokoban-solver#2]
$ java SokobanTester
    IO Exception occured
    javax.imageio.IIOException: Can't read input file!
            at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
            at MainFrame.getTopPanel(MainFrame.java:172)
            at MainFrame.init(MainFrame.java:78)
            at MainFrame.<init>(MainFrame.java:61)
            at SokobanTester.main(SokobanTester.java:13)
    
    $ java SokobanTester < assholesokoban.txt
    IO Exception occured
    javax.imageio.IIOException: Can't read input file!
            at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
            at MainFrame.getTopPanel(MainFrame.java:172)
            at MainFrame.init(MainFrame.java:78)
            at MainFrame.<init>(MainFrame.java:61)
            at SokobanTester.main(SokobanTester.java:13)

It's broken.

**Comment by chrispk23** [comment]
I solved it as follows:
    >javac *.java
    >cd ..
    >java -cp ./src: SokobanTester

The problem is it is trying to load the img/ directory from where you execute.  So you need to execute from one directory up and then specify the classpath.
